### ISSUE TITLE
Mostrar na galeria de vitrines, a descrição do campo de apresentação para as vitrinas que foram desenvolvidas com formulários

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wp-vitrines#22]
Campo a ser mostrado

![image](https://user-images.githubusercontent.com/10047460/215172516-30307c57-e318-481c-b0df-d13621122d02.png)

Onde: 

![image](https://user-images.githubusercontent.com/10047460/215173268-10806f9e-307b-4958-954a-575ea4b4e545.png)

**Comment by marcoslmori** [comment]
@pintoros validar a necessidade

**Comment by wilsonmoura** [comment]
@marcoslmori ajustes realizados. Favor validar.

**Comment by pintoros** [comment]
Wilson, essa é uma página provisória, usada para instâncias que têm menos de 10 vitrines.
Seria melhor se mantivesse essa característica independente da construção no formulário ou não. 
Nesse caso deveria habilitar o campo Apresentação do formulário padrão. É lá que aparecem as descrições.
Obrigada

**Comment by marcoslmori** [comment]
Plugin testado nas instâncias de vitrinas da BVS  Brasil e de Saúde Indígena, funcionou sem quebrar a instância e foi solicitado para o ITI atualizar o Plugin da instância de produção da Saúde Indígena

**Comment by pintoros** [comment]
Obrigada!
Vou pedir para a BVS Brasil . No regional já não lincamos essa página.

Seria interessante que fosse feito o ajuste no plugin para distribuição.
Mas vou pedir isso também.

Abraço



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:0da100fb-a966-42a4-a297-acf52a764fce]

________________________________
De: Marcos Luis Mori ***@***.***>
Enviado: terça-feira, 31 de janeiro de 2023 11:48
Para: bireme/wp-vitrines ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/wp-vitrines] Mostrar na galeria de vitrines, a descrição do campo de apresentação para as vitrinas que foram desenvolvidas com formulários (Issue #22)


Plugin testado nas instâncias de vitrinas da BVS Brasil e de Saúde Indígena, funcionou sem quebrar a instância e foi solicitado para o ITI atualizar o Plugin da instância de produção da Saúde Indígena

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwp-vitrines%2Fissues%2F22%23issuecomment-1410496997&data=05%7C01%7Cpintoros%40paho.org%7C3ecdbb63c8234d92d81b08db039a375b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638107733115866655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a0sb5%2Ff0FV7sIPSE6kFPoNYltW2ELgKfWCo03SgjVkc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4CAOIR4T53L5TNUDGTWVEQ3ZANCNFSM6AAAAAAUJAZBHM&data=05%7C01%7Cpintoros%40paho.org%7C3ecdbb63c8234d92d81b08db039a375b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638107733115866655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W5a0BA1r0JtMccMJafs%2B90oqy61vk%2Fm7eSRKaQy%2BhIk%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
